// clients/live-angular/src/index.ts
import {
  computed,
  inject,
  InjectionToken,
  makeEnvironmentProviders,
  signal,
  type EnvironmentProviders,
  type Signal,
  type WritableSignal
} from "@angular/core";
import {
  BlueTuskLiveClient,
  type LiveKey,
  type LiveQuery,
  type LiveQueryState,
  type LiveSubscriptionRequest
} from "@bluetusk/live";

export const BLUE_TUSK_LIVE_CLIENT = new InjectionToken<BlueTuskLiveClient>(
  "BLUE_TUSK_LIVE_CLIENT"
);

export function provideBlueTuskLive(client: BlueTuskLiveClient): EnvironmentProviders {
  if (client === null || client === undefined) {
    throw new TypeError("A BlueTuskLiveClient is required.");
  }

  return makeEnvironmentProviders([
    { provide: BLUE_TUSK_LIVE_CLIENT, useValue: client },
    {
      provide: BlueTuskLiveAngular,
      useFactory: () => new BlueTuskLiveAngular(inject(BLUE_TUSK_LIVE_CLIENT))
    }
  ]);
}

export class AngularLiveQuery<
  TRow,
  TKey extends LiveKey,
  TParameters extends object
> {
  readonly #query: LiveQuery<TRow, TKey, TParameters>;
  readonly #state: WritableSignal<LiveQueryState<TRow>>;
  readonly #unsubscribe: () => void;

  readonly state: Signal<LiveQueryState<TRow>>;
  readonly rows: Signal<readonly TRow[]>;
  readonly phase: Signal<LiveQueryState<TRow>["phase"]>;
  readonly error: Signal<Error | null>;

  constructor(query: LiveQuery<TRow, TKey, TParameters>) {
    this.#query = query;
    this.#state = signal(query.state);
    this.state = this.#state.asReadonly();
    this.rows = computed(() => this.#state().rows);
    this.phase = computed(() => this.#state().phase);
    this.error = computed(() => this.#state().error);
    this.#unsubscribe = query.subscribe((state) => this.#state.set(state));
  }

  start(): void {
    this.#query.start();
  }

  stop(): void {
    this.#query.stop();
  }

  destroy(): void {
    this.#unsubscribe();
    this.#query.stop();
  }
}

export class BlueTuskLiveAngular {
  readonly #client: BlueTuskLiveClient;

  constructor(client: BlueTuskLiveClient) {
    this.#client = client;
  }

  createQuery<TRow, TKey extends LiveKey, TParameters extends object>(
    request: LiveSubscriptionRequest<TParameters>
  ): AngularLiveQuery<TRow, TKey, TParameters> {
    return new AngularLiveQuery(this.#client.createQuery<TRow, TKey, TParameters>(request));
  }
}

// clients/live-react/src/index.ts
import { useEffect, useMemo, useSyncExternalStore } from "react";
import {
  type BlueTuskLiveClient,
  type LiveKey,
  type LiveQueryState,
  type LiveSubscriptionRequest
} from "@bluetusk/live";

export function useBlueTuskLiveQuery<
  TRow,
  TKey extends LiveKey,
  TParameters extends object
>(
  client: BlueTuskLiveClient,
  request: LiveSubscriptionRequest<TParameters>
): LiveQueryState<TRow> {
  const query = useMemo(
    () => client.createQuery<TRow, TKey, TParameters>(request),
    [client, request]
  );
  const state = useSyncExternalStore(
    (onStoreChange) => query.subscribe(() => onStoreChange()),
    () => query.state,
    () => query.state
  );

  useEffect(() => {
    query.start();
    return () => query.stop();
  }, [query]);

  return state;
}
